### ISSUE TITLE
Error Running Demo

### ISSUE THREAD

**Issue by alckasoc** [xingyizhou/GTR#10]
Hello, I'm having trouble running the inference (the "Demo" section in the README). Below is a notebook link showing the setup and error.

[Here](https://colab.research.google.com/drive/1fx_FNGS9DX2iYVufRMErgyzuiNJF_HCt?usp=sharing) is the link to the notebook.

Let me know if anything else needs to be provided.

Much appreciated!

**Comment by xingyizhou** [comment]
Thank you for raising this issue. This is due to an inconsistency in a [recent detectron2 commit](https://github.com/facebookresearch/detectron2/commit/2409af0bf0d4bdcc685feb6d2c7fd659828acac4). A simple fix can be reverting detectron2 to the version before this commit. I'll patch an update to fix this soon.

**Comment by xingyizhou** [comment]
It should have been fixed in [this commit](https://github.com/xingyizhou/GTR/commit/1111a462871dcca5291bfb080639fb6fd5652897).
